feat: update the unpublished state
graasp/graasp pull request #1226
Opened 2024-07-19 12:44 UTC by ReidyT

- also handle the state where the item is unpublished and outdated

2024-07-19 14:51 UTC, spaenleh approved these changes

2024-07-22 08:14 UTC, pyphilia approved these changes

2024-07-22 15:46 UTC, pyphilia requested changes
Readme:
- I would remove all mentions to Library, so we're agnostic of the frontend.
- I would add more reference to the publication status in the explanation of the endpoints, you mentioned some status automatically transitions, but I couldn't find it back in the descriptions of the endpoints.
- Maybe add details about the tables related to the publication. I believe you don't store all the publicationStatus (`ItemTypeNotAllowed` for instance?)   

Mermaid graph:
- can `IsItemAllowed` have a different layout? It looks like it's a status. Actually I think it should be in the losange just after. Same for `isParentPublished`.
- why do `Invalid`, `ItemTypeNotAllowed` go to a point? I think it can just stop at the status.
- what happens if an item `NotPublic` get updated?

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +This document outlines the publication process for items within the Library system. Due to the involvement of multiple services, this specification covers all relevant services.
```suggestion
This document outlines the publication process for items, covering all relevant services (Publication, Validation).
```
you can correct the service's names.

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +The `PublicationService` calculates the current publication status of an item. This information is crucial for other services to determine appropriate actions, such as rejecting queries or returning
```suggestion
The `PublicationService` computes the current publication status of an item. This information is crucial for other services to determine appropriate actions, such as rejecting queries or returning status details.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - Preventing children publication when the parent is already published, are currently implemented only in the frontend.
```suggestion
  - Preventing children publication when the parent is already published, is currently implemented only in the frontend.
```
I would actually highlight this part with a warning, or link an issue for a future implementation.

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - Currently only folders are allowed to be published.
```suggestion
  - Only folders are allowed to be published.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +- **Unpublished**: The item is not yet published in the Library.
```suggestion
- **Unpublished**: The item is not yet published.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +- **Outdated**: The item is currently published but has been updated, necessitating re-validation.
```suggestion
- **Outdated**: The item is currently published but has been updated, requiring the item to be validated again.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - Currently, outdated items remain in the Library without removal, but this behavior might change to include a warning.
```suggestion
  - Outdated items remain published despite being outdated.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - Successful validation transitions the item to Published.
```suggestion
  - Successful validation transitions the item to `Published`.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - Invalid validation transitions the item to Invalid.
```suggestion
  - Invalid validation transitions the item to `Invalid`.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +- **Published**: The item is successfully published in the Library.
```suggestion
- **Published**: The item is successfully published.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - Updating the item changes the status to Outdated.
```suggestion
  - Updating the item changes the status to `Outdated`.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - Unpublishing changes it to ReadyToPublish.
```suggestion
  - Unpublishing changes it to `ReadyToPublish`.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - If not updated, it transitions to Published.
```suggestion
  - If not updated, it transitions to `Published`.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - Updating the item reverts the status to Unpublished.
```suggestion
  - Updating the item reverts the status to `Unpublished`.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +The `ValidationService` allows to validate an item or to retrieve an item's validation. This service is crucial to ensure that an item is validated before publishing it in the Graasp's Library.
```suggestion
The `ValidationService` allows to validate an item or to retrieve an item's validation. This service is crucial to ensure that an item is validated before publishing it.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +    - Validation is asynchronous with websocket feedback.
```suggestion
    - Validation is asynchronous. Websocket feedbacks are sent to the frontend ....
```
complete with websocket messages, doesn't have to be precise, but would be helpful to know when.

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +    - Successful validation automatically publishes the item to the Graasp Library (private items become public).
```suggestion
    - Successful validation automatically publishes the item.
    - Private items become public.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +The `PublishService` manages the item's publications in the Graasp's Library. An item should be validated to be published in the Library.
```suggestion
The `PublishService` manages the item's publications. An item should be validated to be published.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - **Description:** Publishes the item to the Library.
```suggestion
  - **Description:** Publishes the item.
```

2024-07-22 15:46 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +  - **Description:** Unpublishes the item from the Library.
```suggestion
  - **Description:** Unpublishes the item.
```

2024-07-24 11:37 UTC, pyphilia approved these changes
So if I understand correctly, PublicationService does not have a corresponding entity, it uses other services to compute a state? Maybe let's add this in the docs.
Maybe let's also add description about what we save in the db (item validation, published)

2024-07-24 11:37 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +This service use the `Item`, `ItemTag`, `ItemValidationGroup` and `ItemPublished` entities to compute the item's state.
```suggestion
This service uses the `Item`, `ItemTag`, `ItemValidationGroup` and `ItemPublished` entities to compute the item's state.
```

2024-07-24 11:37 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +The service determines a `PublicationStatus`, defined in the SDK, for each item. Below is a description of the possible statuses:
item's state = Publication status right? Maybe we can merge these sentences.

2024-07-24 11:37 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +    - `200 OK`: The item exists.
Might be interesting to define the structure? Or at least the type name.

2024-07-24 11:37 UTC, pyphilia commented on src/services/item/plugins/publication/README.md
> +> If a children is already published, it's still published as a single item.
```suggestion
> If a child is already published, it's still published as a single item.
```

2024-07-25 14:08 UTC, merged