refactor(schemas): remove refs of app schemas
graasp/graasp pull request #1431
Opened 2024-09-27 11:00 UTC by Defferrard

2024-09-27 13:51 UTC, pyphilia requested changes

2024-09-27 13:51 UTC, pyphilia commented on src/schemas/ajvFormats.ts
> +  ajv.addFormat('strongPassword', /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$/);
Duplicate?

2024-09-30 07:01 UTC, ReidyT approved these changes
Really nice, LGTM! Good job 🫠 I just let you a small suggestion

2024-09-30 08:44 UTC, spaenleh approved these changes
Looks good !

2024-09-30 08:44 UTC, spaenleh commented on src/services/item/plugins/app/appData/schemas.ts
> +    200: appDataSchemaRef,
```suggestion
    [AtatusCodes.OK]: appDataSchemaRef,
```

2024-09-30 08:44 UTC, spaenleh commented on src/services/item/plugins/app/appData/schemas.ts
> +    200: appDataSchemaRef,
Same here.

2024-09-30 08:44 UTC, spaenleh commented on src/services/item/plugins/app/appData/schemas.ts
> +    200: customType.UUID(),
Also here

2024-09-30 08:44 UTC, spaenleh commented on src/services/item/plugins/app/appData/schemas.ts
> +    200: Type.Array(appDataSchemaRef),
Here too

2024-10-01 12:43 UTC, pyphilia approved these changes

2024-10-01 12:47 UTC, merged