feat: lint openapi during git actions
graasp/graasp pull request #1527
Opened 2024-10-17 05:22 UTC by Defferrard

2024-10-17 12:56 UTC, spaenleh reviewed
Looks good ! Should we also update the tests file ?

2024-10-17 13:07 UTC, Defferrard commented
> Looks good ! Should we also update the tests file ?

If you mean the `test/app.ts`, I'd say yes, but I did not be able to make it works... I've probably didn't put enough effort in it because I think it is out of the scope of this PR

2024-10-18 08:43 UTC, ReidyT reviewed
The code looks good, but I still have a few questions before approving your PR ^^.

2024-10-18 08:43 UTC, ReidyT commented on package.json
> +    "@quobix/vacuum": "0.13.6",
I think you can put it in dev dependencies?

2024-10-18 08:43 UTC, ReidyT commented on package.json
> +    "fastify-cli": "7.0.1",
same here?

2024-10-18 08:43 UTC, ReidyT commented on src/server.ts
Is this file still useful? Why don't we just use the new `fastify` file? Also, why do we have moved the start function in the other file?

2024-10-18 09:19 UTC, Defferrard commented on src/server.ts
So we can retrieve the export fastify instance without running the function `start()`

2024-10-18 09:52 UTC, ReidyT commented on src/server.ts
Mmmh okay thanks for your explanation! But in this case, could we move the code in the server.ts directly where this file is imported? I mean, we have an entire file just to start a method we imported from another file 😅

2024-10-18 10:43 UTC, ReidyT commented on src/server.ts
My bad, I thought server.ts was used in app, but its the entry point ^^

2024-10-18 10:43 UTC, ReidyT approved these changes

2024-10-18 10:48 UTC, pyphilia requested changes
LGMT! But I think the vaccum script does not use the right file?

2024-10-18 10:48 UTC, pyphilia commented on package.json
> +    "openapi:lint": "vacuum lint ./openapi.json"
Shouldn't it be `.openapi.json`?  I have a personal preference for `openapi.json` though.

```suggestion
    "openapi:lint": "vacuum lint ./.openapi.json"
```

2024-10-25 10:01 UTC, pyphilia approved these changes

2024-10-25 10:07 UTC, merged