fix: do not encode redirection url for password
graasp/graasp pull request #1535
Opened 2024-10-17 11:41 UTC by pyphilia

fix #1530

2024-10-17 12:38 UTC, spaenleh requested changes
Thank you for the fix, let me know what you think ?

2024-10-17 12:38 UTC, spaenleh commented on src/services/auth/plugins/password/index.test.ts
> +describe('Regression tests', () => {
Should this be named differently ? 

`Flow tests` maybe instead of singling it out as a `regression test` ?

2024-10-17 12:38 UTC, spaenleh commented on src/services/auth/plugins/password/index.test.ts
> +    const response = await app.inject({
Should we check the status code before sending this request ?

2024-10-17 12:56 UTC, Defferrard approved these changes
I agree with what @spaenleh said, otherwise LGTM!

2024-10-18 08:34 UTC, ReidyT approved these changes
LGTM 🌨️

2024-10-18 08:48 UTC, spaenleh approved these changes
🎩

2024-10-18 08:49 UTC, spaenleh commented
@pyphilia just looks like the expected status code is not `200` but `303` as this is a `redirect`

2024-10-18 09:05 UTC, merged