feat: split upload csv
graasp/graasp pull request #1561
Opened 2024-10-22 08:43 UTC by pyphilia

close #1560

2024-10-22 09:24 UTC, pyphilia commented on src/services/member/schemas.ts
> -const compositeCurrentMemberSchema = Type.Composite([
Remove.

2024-10-23 07:56 UTC, spaenleh requested changes
Looks good, thank you for the refactor and the tests, let me know about the comment.

2024-10-23 07:56 UTC, spaenleh commented on src/services/item/plugins/invitation/schema.ts
> +    }),
I think we are missing the potential error codes.

2024-10-23 07:56 UTC, spaenleh commented on src/services/item/plugins/invitation/schema.ts
> +    [StatusCodes.OK]: Type.Array(
Same here, I think we should add the potential error codes.

2024-10-23 07:56 UTC, spaenleh commented on src/services/item/plugins/invitation/test/index.test.ts
> +          for (const inv of group.invitations) {
You only test invitations, should we also test the memberships created ? Are there any in this test ?

2024-10-24 14:01 UTC, spaenleh approved these changes

2024-10-24 14:04 UTC, merged