docs: add docs for app data file endpoints
graasp/graasp pull request #1584
Opened 2024-10-30 09:16 UTC by pyphilia

ref #1528

2024-10-30 11:01 UTC, spaenleh requested changes
Nice ! I think we should change some things before merging. 📜

2024-10-30 11:01 UTC, spaenleh commented on src/services/item/plugins/app/appData/plugins/file/schema.ts
>      id: customType.UUID(),
Same comment here, can we specify which `id` this is ?

2024-10-30 11:01 UTC, spaenleh commented on src/services/item/plugins/app/appData/plugins/file/schema.ts
> +    id: customType.UUID(),
Also here.

2024-10-30 11:01 UTC, spaenleh commented on src/services/item/plugins/app/appData/plugins/file/index.ts
>      method: HttpMethod.Post,
Same question here about the use of `fastify.route` instead of the shorthand.

2024-10-30 11:13 UTC, pyphilia commented on src/services/item/plugins/app/appSetting/plugins/file/index.ts
>      method: HttpMethod.Post,
Not sure, but it was not the goal of the PR so I didn't change it.

2024-10-31 10:15 UTC, spaenleh approved these changes

2024-11-01 10:14 UTC, pyphilia commented on src/services/item/plugins/app/appData/plugins/file/schema.ts
> +    [StatusCodes.OK]: Type.String({ format: 'uri' }),
I think it does, it is for regular files or thumbnails that it doesn't.

https://github.com/graasp/graasp/blob/908a278f1116f8b34bf34ba1a9463f5ffccc3dcf/src/services/item/plugins/app/appData/plugins/file/service.ts#L96

2024-11-01 14:22 UTC, merged