docs: add documentation for file endpoints
graasp/graasp pull request #1585
Opened 2024-10-30 10:06 UTC by pyphilia

2024-10-30 10:57 UTC, spaenleh requested changes
Maybe we need a bit more info ?

2024-10-30 10:57 UTC, spaenleh commented on src/services/item/plugins/file/schema.ts
> +        description: 'Folder id in which the upload should be uploaded.',
```suggestion
        description: 'Folder id in which the uploaded files should be created.',
```

2024-10-30 10:57 UTC, spaenleh commented on src/services/item/plugins/file/schema.ts
> +    previousItemId: Type.Optional(customType.UUID()),
Add a description ?

2024-10-31 07:34 UTC, ReidyT approved these changes
LGTM 🫕

2024-10-31 09:45 UTC, spaenleh approved these changes

2024-11-01 10:35 UTC, merged