docs: add docs for member profile endpoints
graasp/graasp pull request #1586
Opened 2024-10-30 10:58 UTC by pyphilia

ref #1528

2024-10-30 12:56 UTC, spaenleh requested changes
Nice, I would adapt the naming a bit.

2024-10-30 12:56 UTC, spaenleh commented on src/services/member/plugins/profile/controller.ts
> +      schema: updateOwnMemberProfile,
```suggestion
      schema: updateOwnProfile,
```

2024-10-30 12:56 UTC, spaenleh commented on src/services/member/plugins/profile/schemas.ts
> +const inputPublicProfileMemberSchemaRef = customType.StrictObject({
This is not a ref anymore.
```suggestion
const inputPublicProfileMemberSchema = customType.StrictObject({
```

2024-10-30 12:56 UTC, spaenleh commented on src/services/member/plugins/profile/schemas.ts
> +  operationId: 'getOwnMemberProfile',
```suggestion
  operationId: 'getOwnProfile',
```

2024-10-30 12:56 UTC, spaenleh commented on src/services/member/plugins/profile/schemas.ts
> +export const updateOwnMemberProfile = {
```suggestion
export const updateOwnProfile = {
```

2024-10-30 12:56 UTC, spaenleh commented on src/services/member/plugins/profile/schemas.ts
> +  operationId: 'createOwnMemberProfile',
```suggestion
  operationId: 'createOwnProfile',
```

2024-10-30 17:16 UTC, spaenleh approved these changes
🌻

2024-10-31 07:18 UTC, ReidyT approved these changes

2024-10-31 08:23 UTC, merged