feat(refactor): simplify the short links by using new SDK types
graasp/graasp pull request #1612
Opened 2024-11-04 16:13 UTC by ReidyT

2024-11-05 13:06 UTC, pyphilia requested changes
LGTM! I just have a question about the schema, it's a nice refactor!

2024-11-05 13:06 UTC, pyphilia commented on src/services/item/plugins/shortLink/schemas.ts
> +    }),
The description does not match the schema. 
- Missing returned empty object. If empty does it return with another status code?
- Also does it always return all three platforms?

2024-11-06 09:21 UTC, ReidyT commented on src/services/item/plugins/shortLink/repository.ts
> +      const updatedEntity = await this.getOne(entity.alias);
As discussed earlier, I have to return it to invalidate the query cache correctly.

2024-11-06 12:36 UTC, spaenleh approved these changes
Very clean. I like how you defined the DTO class, which does the explicit mapping to the exit type. Maybe we should annotate the function type explicitly ? Anyway I think it is ver clear and readable. Well done ! 👍

2024-11-06 14:14 UTC, pyphilia approved these changes
LGTM! I added suggestions to improve even more your schema ^^

2024-11-06 14:14 UTC, pyphilia commented on src/services/item/plugins/shortLink/schemas.ts
> +      Type.Object(
You could use `customType.StrictObject` to avoid repeating `additionalProperties: false`

2024-11-06 14:14 UTC, pyphilia commented on src/services/item/plugins/shortLink/schemas.ts
> +      Type.Object({}, { additionalProperties: false }),
Same as above.

2024-11-06 14:14 UTC, pyphilia commented on src/services/item/plugins/shortLink/schemas.ts
> +        { additionalProperties: false },
I think you can add `minProperties: 1` to apply "at least one"

2024-11-06 14:32 UTC, merged