docs: add global tags for openapi
graasp/graasp pull request #1617
Opened 2024-11-06 08:59 UTC by pyphilia

- add cli to generate html report from vacuum
- add global tags definition

2024-11-06 14:01 UTC, spaenleh requested changes
Good work, I propose a few changes to the descriptions. 📖

2024-11-06 14:01 UTC, spaenleh commented on src/plugins/swagger.ts
> +        { name: 'tag', description: 'Endpoints related to visibility tags' },
To change once the renaming PR is merged.

2024-11-06 14:43 UTC, ReidyT approved these changes
Really nice!

2024-11-07 13:15 UTC, pyphilia commented on package.json
> +    "openapi:report": "vacuum html-report ./openapi.json vacuum-report.html"
I actually tried but it was not really working. Actually I think the generation is not so accurate too, but let's see for next time.

2024-11-07 13:22 UTC, merged