fix: add documentation and details to published schemas
graasp/graasp pull request #1642
Opened 2024-11-14 14:46 UTC by pyphilia

ref #1528

2024-11-18 12:08 UTC, ReidyT approved these changes

2024-11-19 10:10 UTC, MatveyK requested changes
Looks good to me. Just a few remarks on phrases employed.

2024-11-19 10:10 UTC, MatveyK commented on src/services/item/plugins/publication/published/schemas.ts
> +  summary: 'Get most recent published items',
I would say 'Get most recently published items'.

2024-11-19 10:10 UTC, MatveyK commented on src/services/item/plugins/publication/published/schemas.ts
> +  description: 'Publish an item, that will become listed in the Library.',
I would rather say 'Publish an item. It will become listed in the Library.

2024-11-19 10:10 UTC, MatveyK commented on src/services/item/plugins/publication/published/schemas.ts
> +  description: 'Unpublish an item, that will not be available anymore on the Library.',
And here 'Unpublish an item. It will stop being available in the Library.'

2024-11-19 14:46 UTC, MatveyK approved these changes
👍🏾

2024-11-20 09:50 UTC, merged