feat: update member password
graasp/graasp pull request #219
Opened 2022-07-06 16:10 UTC by victorggonzalez

This PR contains necessary functions to perform the password update operation

2022-07-10 10:55 UTC, victorggonzalez commented
I have included the updatePassword procedure inside auth. As we discussed, this way we have a dedicated endpoint to perform this operation

2022-07-11 07:41 UTC, pyphilia requested changes
Thanks for the change, I've added my comments, let me know if you have questions 🚥

2022-07-11 07:41 UTC, pyphilia commented on src/plugins/auth/auth.ts
> +      const saltRounds = 10;
Factor out in constants/settings.

2022-07-11 07:41 UTC, pyphilia commented on src/plugins/auth/auth.ts
> +          delete body['currentPassword'];
You don't need to do this right?

2022-07-11 07:41 UTC, pyphilia commented on src/plugins/auth/auth.ts
> +        }
To simplify, I would do `if(!verified) throw ...` so you don't have to use a else clause.

2022-07-11 07:41 UTC, pyphilia commented on src/services/members/service-api.ts
Remove all changes made in this file, since it is used in auth now.

2022-07-11 07:41 UTC, pyphilia commented on src/util/graasp-error.ts
> +        message: 'Current password is invalid. Please try again.',
Could you create a branch in translations as well? Or an issue? So we can later translate the errors.

2022-07-11 07:55 UTC, pyphilia requested changes

2022-07-11 07:55 UTC, pyphilia commented on src/plugins/auth/auth.ts
> +        // verify that input current password is the same as the stored one
Actually you never check that actor is the member. But actually we should go for the following endpoint `/members/update-password` and assume it's for the current member. We will have another endpoint for admin where we can precise the member id.

2022-07-13 10:08 UTC, pyphilia requested changes
It looks good! I've added some more comments but it looks good to merge! 🛍️

2022-07-13 10:08 UTC, pyphilia commented on src/plugins/auth/auth.ts
> +        // }
Remove?

2022-07-13 16:43 UTC, merged