feat: not return password value
graasp/graasp pull request #222
Opened 2022-07-08 15:40 UTC by victorggonzalez

2022-07-11 07:30 UTC, pyphilia requested changes
Thanks for the PR! 
But actually, from what we decided for the password mechanism, we don't need the password field (even as a boolean). So I think the best solution to not return the password is to add a schema to this endpoint. Let me know if it's not clear^^

2022-07-11 08:26 UTC, victorggonzalez commented
Done! Let me know what you think of this

2022-07-11 14:39 UTC, pyphilia requested changes
Looks good! Do you think you could update the test for /members/current? (member.test.ts) We would like to test that password does not exist in the response, but the other fields do.

2022-07-11 14:39 UTC, pyphilia commented on src/services/members/schemas.ts
> +  // params: { $ref: 'http://graasp.org/#/definitions/idParam' },
Remove.

2022-07-11 14:39 UTC, pyphilia commented on src/services/members/schemas.ts
> +        extra: { type: 'object', additionalProperties: true },
Maybe add createdAt and updatedAt?
Change to `additionalProperties: false`?

2022-07-13 10:04 UTC, pyphilia approved these changes

2022-07-13 12:14 UTC, merged