chore: ignore authorization header error in sentry
graasp/graasp pull request #549
Opened 2023-08-11 15:14 UTC by pyphilia

This error happens like always and is suppose to happen, I think it makes sense to ignore it. Let me know what you think.

![Screenshot 2023-08-11 at 17 12 04](https://github.com/graasp/graasp/assets/11229627/41e31bca-44a0-412a-92db-34edc28dc722)

2023-08-11 15:46 UTC, dialexo requested changes
Shouldn't we ignore those directly in the sentry dashboard? That way we still receive them but they are filtered at the provider, and we have flexibility in adding / removing them.

2023-08-14 06:05 UTC, spaenleh commented
I understand why we would like to ignore it in the dashboard, but there are no "ignore indefinitely" option. For reference these are the options:
<img width="313" alt="Screenshot 2023-08-14 at 08 03 55" src="https://github.com/graasp/graasp/assets/39373170/a7f33cf0-36ab-4d10-bb50-457152f1e4a0">
So unless we ignore it for a 100 years ...

2023-08-14 07:30 UTC, dialexo commented
> I understand why we would like to ignore it in the dashboard, but there are no "ignore indefinitely" option. For reference these are the options: <img alt="Screenshot 2023-08-14 at 08 03 55" width="313" src="https://user-images.githubusercontent.com/39373170/260369903-a7f33cf0-36ab-4d10-bb50-457152f1e4a0.png"> So unless we ignore it for a 100 years ...

Actually if you click on the ignore button directly (not on the arrow menu), it seems the issue is completely ignored. See https://graasp.sentry.io/issues/4264884885/?project=6177699&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=1

2023-08-14 07:34 UTC, pyphilia commented
But you still send it to sentry, and we're limited on the number of transactions as well. Won't also it continue to trigger on slack if we ignore it in the dashboard only?

2023-08-14 07:42 UTC, spaenleh commented
@dialexo Nice find, i didn't even think about checking the button directly ... 🙃

2023-08-14 07:43 UTC, dialexo commented
I've found some docs on errors quota: 
https://docs.sentry.io/product/accounts/quotas/#inbound-data-filters
Do we want to setup inbound filters at https://graasp.sentry.io/settings/projects/graasp-core/filters/data-filters/ ?

2023-08-14 07:46 UTC, pyphilia commented
Sponsored plan:
- 5M errors
- 10M performance units
- 10K replays
- 10G Battachments
But we're really far from the max, so it's okay to filter from sentry.

2023-08-14 09:23 UTC, closed without merging