fix: use mailer in itemMembership service, fix notification
graasp/graasp pull request #565
Opened 2023-08-18 12:06 UTC by pyphilia

close #564

2023-08-21 14:00 UTC, dialexo requested changes
The change in `declarations.d.ts` is not needed, but you can actually remove the dangling legacy property entirely.

2023-08-21 14:00 UTC, dialexo commented on src/declarations.d.ts
I've actually removed the `hosts` decoration in #471, I don't think it makes much sense to decorate it at runtime rather than consuming it directly from the constants file. Not sure why I forgot to remove it from the declarations, but I think you should remove the `hosts` property altogether.

2023-08-22 09:01 UTC, pyphilia commented on src/declarations.d.ts
Good to know, I was not sure if it was actually used. I've removed it everywhere, the only "big" change is in h5p let me know if it looks correct.

2023-08-24 12:09 UTC, dialexo approved these changes
LGTM 🍄

2023-08-25 11:20 UTC, merged