feat: add action triggers to download item, like, unlike, search item
graasp/graasp pull request #667
Opened 2023-10-26 10:52 UTC by LinaYahya

closes #663

2023-11-03 11:11 UTC, spaenleh requested changes
Thank you for these changes, I would just change the queryParam name to something clearer.

2023-11-03 11:11 UTC, spaenleh commented on src/services/item/plugins/importExport/index.ts
> +  fastify.route<{ Params: { itemId: string }; Querystring: { type?: string } }>({
If possible I would use a more descriptive argument name:
```suggestion
  fastify.route<{ Params: { itemId: string }; Querystring: { actionType?: string } }>({
```

2023-11-03 11:11 UTC, spaenleh commented on src/services/item/plugins/published/plugins/search/index.ts
> +        extra: { ...(body as any) },
Do you have an issue with the types here ? I am ok to keep it, but if possible I would prefer `unknown`.

2023-11-08 12:08 UTC, pyphilia requested changes
Thanks for your PR, I'll approve once you add the action type in sdk!

2023-11-08 12:08 UTC, pyphilia commented on src/services/item/plugins/itemLike/index.ts
> +        await actionService.postMany(member, buildRepositories(manager), request, [action]);
Let's create the action only after the post.

2023-11-08 12:08 UTC, pyphilia commented on src/services/item/plugins/itemLike/index.ts
> +        await actionService.postMany(member, buildRepositories(manager), request, [action]);
Same as above.

2023-11-08 12:08 UTC, pyphilia commented on src/services/item/plugins/importExport/index.ts
> +          type: actionType,
Maybe we want to always save an action. Is it possible to set a default value?

2023-11-08 12:08 UTC, pyphilia commented on src/services/item/plugins/importExport/index.ts
> +  fastify.route<{ Params: { itemId: string }; Querystring: { actionType?: string } }>({
Might be interesting to add a comment about what values can this be? Will it refer to where in the ui we clicked? Can this info be added in the extra and have a global action type?

2023-11-08 12:08 UTC, pyphilia commented on src/services/item/plugins/published/plugins/search/index.ts
> +        extra: body as Partial<Action> & Pick<Action, 'type'>,
You can precise the type like this if I'm not mistaken:
`fastify.post<{ Body: Partial<Action> & Pick<Action, 'type'> }>(`

2023-11-08 12:08 UTC, pyphilia commented on src/services/item/plugins/published/plugins/search/index.ts
> +        extra: body as Partial<Action> & Pick<Action, 'type'>,
Also update the schema of the search endpoint accordingly.

2023-11-13 12:07 UTC, spaenleh approved these changes
🍪 Nice !

2023-11-28 14:06 UTC, pyphilia requested changes
Thanks for the PR! I'm a bit concerned about the test that you changed tho?

2023-11-28 14:06 UTC, pyphilia commented on src/services/item/plugins/importExport/test/index.test.ts
> -      }, 1000);
I don't think this should be removed.
What result do you have?

2023-11-28 14:06 UTC, pyphilia commented on src/services/item/plugins/itemLike/index.ts
> +            itemId: item?.id,
```suggestion
            itemId: item.id,
```

2023-11-28 14:06 UTC, pyphilia commented on src/services/item/plugins/itemLike/index.ts
> +            itemId: item?.id,
Maybe let's create the action after performing the like, so that the scope of `action` is smaller.

2023-11-28 14:06 UTC, pyphilia commented on src/services/item/plugins/itemLike/index.ts
> +        };
Same comments as above.

2023-11-28 14:06 UTC, pyphilia commented on src/services/item/plugins/published/plugins/search/index.ts
> +      return searchService.search(member, repositories, body);
Maybe let's perform the search first, then the post action. Otherwise you might end up having an action even though the search failed.

2023-11-28 15:25 UTC, merged